tunnel: <YOUR_TUNNEL_ID>
credentials-file: /users/yourname/.cloudflared/<YOUR_TUNNEL_ID>.json

ingress:
  - hostname: dev.yourdomain.com
    service: http://localhost:3000
  - service: http_status:404